#cheese

import json

from http.server import HTTPServer, BaseHTTPRequestHandler
from socketserver import ThreadingMixIn

from Cheese.appSettings import Settings
from Cheese.cheeseController import CheeseController
from Cheese.adminManager import AdminManager
from Cheese.Logger import Logger
from Cheese.ErrorCodes import Error
from python.authorization import Authorization

#CONTROLLERS

"""
File generated by Cheese Framework

server handler of Cheese Application
"""

class CheeseServerMulti(ThreadingMixIn, HTTPServer):
    """Handle requests in a separate thread."""

class CheeseServer(HTTPServer):
    """Handle requests in one thread."""

class CheeseHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        if (self.path.startswith("/admin")):
            AdminManager.controller(self)
            return
        self.__log()
        if (self.path == "/alive"):
            CheeseController.sendResponse(self, CheeseController.createResponse({"RESPONSE": "Yes"}, 200))
            return
        try:
#GET        
        except Exception as e:
            if (type(e) is SystemError):
                Logger.fail("SystemError occurred", e)
                error = e
                while (len(error.args) > 1):
                    error = error.args[-1]
                Error.sendCustomError(self, error.args[0], 500)
            else:
                Logger.fail("An error unknown occurred", e)
                Error.sendCustomError(self, "Internal server error :(", 500)

    def do_POST(self):
        self.__log()
        try:
#POST
        except Exception as e:
            if (type(e) is SystemError):
                Logger.fail("SystemError occurred", e)
                error = e
                while (len(error.args) > 1):
                    error = error.args[-1]
                Error.sendCustomError(self, error.args[0], 500)
            else:
                Logger.fail("An error unknown occurred", e)
                Error.sendCustomError(self, "Internal server error :(", 500)

    def end_headers(self):
        if (Settings.allowCORS):
            self.send_header("Access-Control-Allow-Origin", "*")
            BaseHTTPRequestHandler.end_headers(self)
        else:
            self.send_header("Content-type", "application/json")

    def log_message(self, format, *args):
        return

    def __log(self):
        Logger.okGreen(f"{self.client_address[0]} - {self.command} \"{self.path}\"")

