#!/usr/bin/env python
# -*- coding: utf-8 -*-

from cheese.appSettings import Settings
from cheese.Logger import Logger
from cheese.databaseControll.postgreDB import PostgreDB
from cheese.databaseControll.SQLserverDB import SQLServerDB

"""
File generated by Cheese Framework

database connection of Cheese Application
"""

class Database:

    def __init__(self):
        pass

    # connect to database
    def connect(self):
        if (Settings.dbDriver == "postgres"):
            self.db = PostgreDB()
        else:
            self.db = SQLServerDB()

        self.db.connect()

    # close connection with database
    def close(self):
        self.db.close()
    
    # select query
    def query(self, sql):
        self.connect()
        ret = self.db.query(sql)
        self.close()
        return ret

    # insert, update ...
    def commit(self, sql):
        self.connect()
        self.db.commit(sql)

    # commit when done
    def done(self):
        self.db.done()
        self.close()

    def rollback(self):
        self.db.rollback()