name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.commits[0].message }} == 'automatic build for pip'
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner
        with:
            ref: main

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' # install the python version needed
          
      - name: Install dependecies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade twine
          python3 -m pip install --upgrade build

      - name: Build
        run: python3 -m build

      - name: Upload to Pypi
        run: python3 -m twine upload --repository testpypi dist/* -u ${{ secrets.PYPIUSERNAME }} -p ${{ secrets.PYPIPASSWORD }}
        