name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner
        with:
            ref: main

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' # install the python version needed
          
      - name: Install dependecies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade twine
          python3 -m pip install --upgrade build
          python3 -m pip install --upgrade GitPython
          python3 -m pip install --upgrade pyodbc
          python3 -m pip install --upgrade psycopg2-binary
          python3 -m pip install --upgrade psycopg2
          python3 -m pip install --upgrade bs4
          python3 -m pip install --upgrade requests
          python3 -m pip install --upgrade CheeseFramework

      - name: Promote version
        run: python3 .github/promoteVersion.py ${{ github.event.commits[0].message }}

      - name: Prepare build
        id: buildPrepare
        run: |
          output=$(python3 .github/prepareMainBranch.py ${{ github.event.commits[0].message }})
          echo "::set-output name=commitMessage::$output"

      - name: Documentation build
        if: github.event.commits[0].message == 'test build' || github.event.commits[0].message == 'build'
        run: python3 .github/docBuild.py

      - name: Only Documentation build
        if: github.event.commits[0].message == 'test build' || github.event.commits[0].message == 'build'
        run: |
          output=$(python3 .github/docBuild.py
          echo "::set-output name=commitMessage::$output"
        
      - name: Build
        if: github.event.commits[0].message == 'test build' || github.event.commits[0].message == 'build' 
        run: python3 -m build

      - name: Upload to Test Pypi
        if: github.event.commits[0].message == 'test build'
        run: python3 -m twine upload --repository testpypi dist/* -u ${{ secrets.PYPIUSERNAME }} -p ${{ secrets.PYPIPASSWORD }}

      - name: Upload to Pypi
        if: github.event.commits[0].message == 'build'
        run: python3 -m twine upload dist/* -u ${{ secrets.PYPIUSERNAME }} -p ${{ secrets.PYPIPASSWORD }}

      - name: commit files
        if: github.event.commits[0].message == 'test build' || github.event.commits[0].message == 'build' || github.event.commits[0].message == 'doc build'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "${{ steps.buildPrepare.outputs.commitMessage }}" -a
          
      - name: push changes
        if: github.event.commits[0].message == 'test build' || github.event.commits[0].message == 'build' || github.event.commits[0].message == 'doc build'
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main  
        